### ISSUE TITLE
Non-standard setting of image in values

### ISSUE THREAD

**Issue by cbrherms** [kha7iq/charts#3]
Currently the `image` section in the `values.yaml` file for the drl-exporter chart splits the image path between `repository` and `name` fields:

```YAML
image:
  repository: ghcr.io
  name: khaliq/drl-exporter
  tag: v2.1.3
  pullPolicy: Always
```

This seems to be a non-standard structure and is causing tools like Renovate to fail, as they expect the full image path (e.g., `ghcr.io/khaliq/drl-exporter`) to be in `repository`. For example, Renovate throws the following error:

```Code
Failed to look up docker package ghcr.io
```

Unless there's a particular reason for having these split, would you consider changing this to the standard format? That would then allow values to be set like:

```YAML
image:
  repository: ghcr.io/khaliq/drl-exporter
  tag: v2.1.3
  pullPolicy: Always
```

To avoid a breaking change, it could use the current way of building the container image value in the pod template if `name` is present, but if not then just use the repository value. e.g.

```YAML
image: "{{ if .Values.image.name }}{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}{{ else }}{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}{{ end }}"
```

This would improve compatibility with automation tools and simplify usage.
